### PR TITLE
Full featured apt package using stdeb

### PR DESCRIPTION
**Pull request by g1itch**
As you suggested this PR is instead of #1675. Maybe squash more?

### CODE REVIEW

**Comment by PeterSurda** [comment]
Yes please squash, and remove `Dockerfile` and `src/bitmessagemain.py` from the PR.

**Comment by g1itch** [comment]
The build process was documented in bionic job of the example `.travis.yml` it's basically
```sh
sudo apt-get install -yq apt-file build-essential debhelper dh-python fakeroot libssl-dev python-all-dev \
    python-msgpack python-qt4 python-setuptools python-stdeb
python setup.py sdist
python setup.py --command-packages=stdeb.command bdist_deb
```

Using `export VERSION=$(python setup.py -V)` you may find the package in `deb_dist/pybitmessage_${VERSION}-1_amd64.deb`. Such name is because it's a program, not library. `python-<libname>_<version_arch>.deb` is for libraries.

**Comment by PeterSurda** [comment]
Yes I'm fixing it.

**Comment by g1itch** [comment]
> Yes please squash, and remove `Dockerfile` and `src/bitmessagemain.py` from the PR.

So you OK with the old deb building procedure in the Dockerfile? Changes to `bitmessagemain` are needed if you want to use `pybitmessage -t` when installed from deb.

**Comment by PeterSurda** [comment]
Won't the `Dockerfile` work if you skip `pybitmessage -t`?

**Comment by g1itch** [comment]
> Won't the `Dockerfile` work if you skip `pybitmessage -t`?

`pybitmessage -t` is used to generate default keys.dat. Then it generates password and edits the config.

**Comment by PeterSurda** [comment]
I thought it was supposed to create the defaults if settingsversion isn't high enough, even if the api* options are already set.

**Comment by g1itch** [comment]
Without installing extra packages and running core tests it's just builds faster.

**Comment by PeterSurda** [comment]
It looks like an overkill to run `pybitmessage -t` just to create a default config file.

**Comment by g1itch** [comment]
> It looks like an overkill to run `pybitmessage -t` just to create a default config file.

Otherwise user should connect to container upon first run and manually enable API and set username and password.

**Comment by PeterSurda** [comment]
I think instead the bmconfigparser should set defaults when it's missing. Then you could create a minimal keys.dat and wouldn't have to run `pybitmessage -t`:

```
[bitmessagesettings]
settingsversion = auto
dontconnect = false
apiusername = aaa
apipassword = bbbb
apiinterface = 0.0.0.0
apienabled = true
```

**Comment by PeterSurda** [comment]
I also don't understand why these two things (Dockerfile and dpkg) are in one PR.

**Comment by g1itch** [comment]
> I also don't understand why these two things (Dockerfile and dpkg) are in one PR.

I removed dpkg use from Dockerfile because it was a documentation for building deb. I can squash those changes with the removal of previous package files.

**Review by PeterSurda — APPROVED** [review]
Ok approved, just fix pylint.

**Comment by g1itch** [comment]
I forgot the apparmor config here.

**Review by PeterSurda — APPROVED** [review]
Ok

**Pull request merged**
