### PR TITLE
An Interface that looks more like an email client

### PR DESCRIPTION
**Pull request by felidosz**
This interface should increase the usability.
 * it looks like more like an ordinary email client
 * the 3 msg-types are separated by tabs
 * you can access the trash folder now
 * the address book is next to the message tab, so you can add more addresses without tab switching
 * if you dont know what a broadcast msg is, you were confused by the radio buttons at the send tab. If you now open the send tab, just start sending a message like an email

BUG
 * There is one bug with the codec in the treeWidgets, so utf8 letters are displayed not correctly

cool would be
 * add address by double clicking on its entry (at the moment, its for changing address label)
 * an additional button below "new identity" called "new broadcast address" for teaching the user easy about the posibility of broadcast messages

screenshots
messages
send
sub
chan

### CODE REVIEW

**Comment by bashrc** [comment]
Looks like a good improvement.

**Comment by pouleta** [comment]
:+1:

**Comment by PeterSurda** [comment]
This looks very nice. Could you also add interfaces for email gateways such as mine: https://mailchuck.com/ ? I could do it myself but I suck at UI.

**Comment by PeterSurda** [comment]
I've been playing with this, there are some minor bugs but otherwise I'm very happy with it. I'm fixing the bugs and I'll try to adjust the UI for email gateways too.

**Comment by mailchuck** [comment]
Check my own fork which builds on this, has fixes and improvements: https://github.com/mailchuck/PyBitmessage

**Comment by pouleta** [comment]
@mailchuck Do you think about to let the user resize the boxes ? Nice work

**Comment by mailchuck** [comment]
That's on the list, in the meantime you can use tooltips as a workaround (just hover the mous over the account and it will display the full bitmessage address as well as label.

**Comment by pouleta** [comment]
nice

**Comment by mailchuck** [comment]
@pouleta , I just made a new release, among other things the "Messages" tab allows you to resize the boxes, like a typical email client. The resizing does not work for channels/subscriptions yet, but I'll get around to it eventually.

**Comment by PeterSurda** [comment]
@felidosz , I'm now helping with official pybitmessage. I will eventually merge my GUI changes which are built on yours, so I'm not merging this particular pull request. Thank you very much for your contribution, if you have further improvement suggestions, I recommend you make pull requests to the https://github.com/mailchuck/PyBitmessage fork. There I can test them faster and they have a better chance of being pushed upstream during normal development lifecycle.

**Comment by felidosz** [comment]
Thank you for finishing the E-Mail like GUI ;)

**Pull request closed without merging**
