### PR TITLE
we need  travis config file

### PR DESCRIPTION
**Pull request by sigoa**
named .travis.yml

### CODE REVIEW

**Comment by g1itch** [comment]
Hurry on, @sigoa, I've set it up:

- `script: src/bitmessagemain.py -t`
- remove `sudo` together with `install` and trailing space after the version
- [squash](/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Comment by PeterSurda** [comment]
#1152 looks more complete than this.

**Comment by g1itch** [comment]
@PeterSurda, #1152 is very large and looks strange for me. Why it's author adding `.travis.yml` having already 75 changed files? Not writing any single comment. Which of that changes were tested at all? He considered unreachable and deleted the code which I use every day. 

I've already tested this version in [my branch](/g1itch/PyBitmessage/tree/testing), please look (click "commits", there is the green check mark on latest one).

**Comment by PeterSurda** [comment]
Yes, I requested that a separate PR be made with only travis-related changes. I also noticed that the "obsolete" code was overzealous and there were other issues with the PR.

**Comment by g1itch** [comment]
I've noticed nobody follows my links:
https://travis-ci.org/g1itch/PyBitmessage/builds/357446666?utm_source=github_status&utm_medium=notification

**Comment by PeterSurda** [comment]
the other example has more configuration data as well as requirements.txt

**Comment by g1itch** [comment]
The `requirements.txt` does not matter. Especially with that fictional dependencies which I see there. Did you hope to test `bitmessagecurses` or `bitmessageqt` that way? More configuration options in this case is making things worse. I just wrote a simple "dry run" mode with which pybitmessage **was really ran** by Travis CI.

**Comment by sigoa** [comment]
the daemon will be auto terminated  on Travis , I believe

**Comment by PeterSurda** [comment]
@g1itch if possible I would like to avoid having to play a referee. It's causing me problems when multiple people are working on the same thing. Therefore, I have a suggestion, there is already a https://bitmessage.slack.com, how about everyone who is contributing registers there (or maybe I have to invite them, I'm not sure), and that can be used for discussing such things, dividing the work, coordinating and so on. There are now too many people contributing for me to coordinate it well just using github. I'll invite Mahendra as well.

**Comment by sigoa** [comment]
@g1itch your Travis is not quite ideal. I made a more comprehensive travis run.

**Comment by sigoa** [comment]
I dont like slack, even gitter is less of a menace

**Comment by PeterSurda** [comment]
@sigoa gitter sounds fine, may actually be even better than slack for this purpose. I created https://gitter.im/Bitmessage, but for some reason I can't invite you.

**Comment by sigoa** [comment]
maybe try https://gitter.im/bit_message/Lobby
chan DevTalk is much easier of course

**Pull request closed without merging**
