### PR TITLE
Fixed flake8 messages for bitmessageqt/bitmessageui.py.

### PR DESCRIPTION
**Pull request by Jeroenvb3**
Fixed some spaces around operators. 

Fixed line length errors. 

Removed unused comment (since 2016) and unused import (since 2012).

### CODE REVIEW

**Review by PeterSurda — APPROVED** [review]

**Comment by PeterSurda** [comment]
Can you sign the commit? Alternatively I can sign it.

**Comment by PeterSurda** [comment]
Ok I'll sign it then.

**Comment by PeterSurda** [comment]
Closed through #2038

**Comment by Jeroenvb3** [comment]
Thank you @PeterSurda . I didn't have time to do it yesterday, I did it just now but saw that you signed it for me. I'll sign future commits from now on.

**Comment by PeterSurda** [comment]
No problem.

**Pull request closed without merging**
