### PR TITLE
Signed-off-by: sigoa <si@goat.si>

### PR DESCRIPTION
**Pull request by sigoa**
clarify that a text is not a BM.

### CODE REVIEW

**Comment by PeterSurda** [comment]
Looks fine, please PGP sign the commit and it's ready to be merged.

**Comment by sigoa** [comment]
well it is partially signed already. you keep demanding very difficult things.

**Comment by sigoa** [comment]
I don't think I can sign the unsigned parts without creating a huge mess.

**Comment by sigoa** [comment]
I give up. no chance.

**Pull request closed without merging**
