### PR TITLE
UI refactoring (part 1)

### PR DESCRIPTION
**Pull request by g1itch**
Hello!

Here is the first part of UI refactoring. What has been done?
 * most dialogs moved into `dialogs` module;
 * made common dialogs code reusable;
 * slightly edited `about.ui` (I think the [wiki page image](https://bitmessage.org/w/images/f/f1/Bitmessagelogo-reduced.png) is also needed here);
 * copyright year made smart.

As usual I ready to drop or squash any commit after review.

### CODE REVIEW

**Comment by PeterSurda** [comment]
Thank you, this is the type of work that is necessary but I don't like doing it myself. I'll review it soon but it's probably ok.

**Comment by g1itch** [comment]
Oops, I have broken `EmailGatewayDialog`. `dialog.exec_()` not returns account.

**Comment by PeterSurda** [comment]
I'm reviewing this now, please no more commits in this PR unless it's a bugfix.

**Comment by g1itch** [comment]
OK, that one was last. EmailGatewayDialog didn't close on one of my computers without self.hide().

**Comment by PeterSurda** [comment]
There's now a conflict with the offline menu, please resolve. I haven't had a time for a full review yet but I'm working on it.

**Comment by g1itch** [comment]
Done rebase.

**Comment by PeterSurda** [comment]
Thank you for this huge amount of work.

**Comment by g1itch** [comment]
Now you may probably close #1081, #1040, #1089. #527 maybe remain as guideline.

**Comment by PeterSurda** [comment]
Done

**Pull request merged**
