### PR TITLE
Add API endpoint to return inbound and outbound connections

### PR DESCRIPTION
**Pull request by 813492291816**
Included is a new API endpoint that returns the inbound and outbound connection information (host, port, and fullyEstablished) as well as the corresponding test in test_api.py.

### CODE REVIEW

**Comment by PeterSurda** [comment]
Looks ok, can you squash?

**Comment by 813492291816** [comment]
Thanks. All squashed.

**Review by PeterSurda — APPROVED** [review]

**Comment by PeterSurda** [comment]
Can you add a user ID to your PGP key and reupload it to your GitHub profile? I can't import it and I can't find a workaround, and without importing the workflow gets disrupted. It doesn't need to be an email address (or at the very least it doesn't need to be a valid email address). If you want to use an email address you can register a mailchuck.com address.

```
$ gpg -vvv --import files/gpg/pubkeys/B14DF20410E5A5BC
gpg: using character set 'utf-8'
# off=0 ctb=c6 tag=6 hlen=3 plen=525 new-ctb
:public key packet:
	version 4, algo 1, created 1604278051, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: B14DF20410E5A5BC
gpg: pub  rsa4096/B14DF20410E5A5BC 2020-11-02  
gpg: key B14DF20410E5A5BC: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

**Comment by PeterSurda** [comment]
I apologise, the problem was on my end, the key looks ok. Now can I also ask you to rebase since there has been a commit merged yesterday?

**Comment by 813492291816** [comment]
It should be rebased now.

**Pull request merged**
