### PR TITLE
Changed copyright year to 2019

### PR DESCRIPTION
**Pull request by sandakersmann**
Changed copyright year to 2019. Also changed start year to 2012 some places since that is what's correct according to Github.

### CODE REVIEW

**Comment by sandakersmann** [comment]
@g1itch Ok, but is it fine that I change 2013 to 2012 in about.ui?

**Comment by g1itch** [comment]
> @g1itch Ok, but is it fine that I change 2013 to 2012 in about.ui?

I don't know because I joined in 2017.

**Comment by sandakersmann** [comment]
This guy did commit stuff in 2012: https://github.com/Bitmessage/PyBitmessage/commits?author=maran

I will revert 2019 back to 2017

**Comment by sandakersmann** [comment]
@g1itch 2019 is now reverted back to 2017 in about.ui

**Comment by PeterSurda** [comment]
I fail to see the point of these changes in copyright dates and am inclined to reject the PR.

**Comment by PeterSurda** [comment]
I think the project should have a policy about this.

**Comment by PeterSurda** [comment]
For the time being I think continuing updating the year is ok.

**Comment by PeterSurda** [comment]
@sandakersmann you have to rebase the branch so that it can be fast-forward-merged.

**Comment by sandakersmann** [comment]
Do I do that with: `git rebase v0.6` ?

**Comment by PeterSurda** [comment]
I think you need to specify upstream as well, and don't forget to sign (if you have autosign in config, that's enough, otherwise you need to specify `-s`.

**Comment by sandakersmann** [comment]
Not sure if this is correct. If not, I can make a new pull request.

**Comment by PeterSurda** [comment]
Looks ok. You should be now able to merge yourself by clicking the green button which says "Merge pull request". If it doesn't work, let me know and @g1itch will do it.

**Comment by sandakersmann** [comment]
That button is grayed out for me.

**Comment by PeterSurda** [comment]
OK I merged it

**Comment by PeterSurda** [comment]
Hmm it didn't work fully as I wanted, it doesn't look like a ff-merge, I will work on it better next time.

**Comment by sandakersmann** [comment]
Does not look like the programmatically replacing of 2017 in `about.ui` is working...
Screenshot from 2019-03-23 18-24-32

**Comment by PeterSurda** [comment]
Well the screenshot matches the the contents of `about.ui`, looks like you made a typo.

**Comment by sandakersmann** [comment]
@g1itch said it was auto updated in this comment:
https://github.com/Bitmessage/PyBitmessage/pull/1434#issuecomment-460657207
That's why I didn't change that.

**Comment by sandakersmann** [comment]
Made a new pull to fix this:
https://github.com/Bitmessage/PyBitmessage/pull/1448

**Comment by PeterSurda** [comment]
I'll have to look at `about.ui`.

**Comment by g1itch** [comment]
Well, I forgot to mention that substitution works only for git repo, not any tarball or release exe file. I hoped you read the code...

**Pull request merged**
