### PR TITLE
Bundling the json and xml extras

### PR DESCRIPTION
**Pull request by g1itch**
Hi!

I'm trying to address #1903. It seems to work at least for the xml: [previous build](https://github.com/g1itch/PyBitmessage/runs/4493264599?check_suite_focus=true#step:4:3640), [current one](https://github.com/g1itch/PyBitmessage/runs/4506307910?check_suite_focus=true#step:4:3643).

### CODE REVIEW

**Comment by g1itch** [comment]
It looks like the appImage has the similar issue. But to fix it there you might add apt packages into [buildbot-config/master.cfg](https://git.bitmessage.org/g1itch/buildbot-config/src/branch/master/master.cfg#L556): `python-jsonrpclib` and `python-defusedxml`.

**Comment by PeterSurda** [comment]
> It looks like the appImage has the similar issue. But to fix it there you might add apt packages into [buildbot-config/master.cfg](https://git.bitmessage.org/g1itch/buildbot-config/src/branch/master/master.cfg#L556): `python-jsonrpclib` and `python-defusedxml`.

I'm trying to move the appimage build into docker but having problems with pkg2image. Moving to docker will gradually allow to specify the build process inside the project repo directly instead of having it split across buildbot server config, worker config and project repo. It will also allow better caching and therefore build speed.

**Review by PeterSurda — APPROVED** [review]

**Comment by g1itch** [comment]
> I'm trying to move the appimage build into docker but having problems with pkg2image. Moving to docker will gradually allow to specify the build process inside the project repo directly

I doubt that it's possible at all. pkg2image itself seems using docker or some container solution if I remember it correctly.

**Comment by PeterSurda** [comment]
> I doubt that it's possible at all. pkg2image itself seems using docker or some container solution if I remember it correctly.

It uses FUSE to mount squashfs, but has a docker mode workaround that extracts instead of mounting, but for some reason it seems broken and noone else appears to trigger this bug.

**Comment by g1itch** [comment]
> But to fix it there you might add apt packages into buildbot-config/master.cfg

Hmm, maybe it's not needed. Let's check the [artifact](https://github.com/g1itch/PyBitmessage/actions/runs/1573138086).

**Comment by g1itch** [comment]
> > But to fix it there you might add apt packages into buildbot-config/master.cfg
> 
> Hmm, maybe it's not needed. Let's check the [artifact](https://github.com/g1itch/PyBitmessage/actions/runs/1573138086).

Seems working: [current](https://buildbot.bitmessage.org/#/builders/14/builds/5332/steps/8/logs/stdio), [patched](https://buildbot.bitmessage.org/#/builders/14/builds/5335/steps/8/logs/stdio).

**Review by PeterSurda — APPROVED** [review]

**Pull request merged**
