### PR TITLE
Improve bootstrap and connection tests

### PR DESCRIPTION
**Pull request by g1itch**
Hello!

I'm modifying the bootstrap test to cover more possible problems during the bootstrap process. There are off course the debug warnings which will be deleted if I found and fix the cause of failures described in #1597.

### CODE REVIEW

**Comment by g1itch** [comment]
The bootstrap test seem to not fail after update of bootstrap servers. So I removed warnings. Now it's just about more tests.

**Comment by g1itch** [comment]
Bootstrap server in knownnodes: https://travis-ci.org/github/Bitmessage/PyBitmessage/builds/739898088

**Comment by g1itch** [comment]
Maybe 2a4872d should be dropped

**Comment by g1itch** [comment]
Adding bootstrap servers to knownnodes was probably introduced in 54e44ea.

**Review by PeterSurda — APPROVED** [review]
Looks ok.

**Pull request merged**
