### PR TITLE
Massive changes to src/bitmessagecli.py

### PR DESCRIPTION
**Pull request by peter-tank**
API service refactoring

* Introspection and multicall API method restored(server side apply)
+ Try import ssl for API server
+ Test mode for `src/api.py`
+ Try compatible to python3(curses and PyQt4 GUI not tested.)

* Mainly changes:
  * Message attachments faults detecting, dump base64 embeded contents to files allowed
  * Multi-line message acceptable in sending(cancel with `Ctrl+D`), and allow resent on 'Connection Error.'
  * Print out detailed API Error returned.
  * Update Contacts list cmd, bcz contact list API returns unEncoded lable
  * Message pull routing refine, mainlly access inbox messages by IDs
  * API connections `SOCKS5` `HTTP` proxy supportted
* UIs
  * Shorten the user cmds inputs
  * Try to replay user last choices.(rest to default selection by input a blank string)
  * A comprehensive command line parser, override configurations read from file `client.dat` in current working directory.(parse API settings from "keys.dat" either, if located in BMs main directory)
  * Message review limited to 380 characters in default and rewinds enabled

default settings `client.dat`
```
[global]
#start_daemon = http://127.0.0.1:8442

[api]
path = 127.0.0.1:8442
type = HTTP

[proxy]
path = 127.0.0.1:1080
type = none
timeout = 30
remotedns = True
```

### CODE REVIEW

**Comment by KM-200** [comment]
pretty massive, but I'm not exactly happy. 

After I fixed  bitmessagemain.py -curses
bitmessageCLI is really of smaller user than ever. just run with --curses, if Qt4 is not available on your system.

**Comment by PeterSurda** [comment]
"The email in this signature doesn’t match the committer email."

**Comment by peter-tank** [comment]
@PeterSurda I revoked this key_id: 75108C80 accidently while playing with pgp...
It might be ok now? i associated mail `30540412+peter-tank@users.noreply.github.com` to the new key and imported to github.

**Comment by peter-tank** [comment]
deprecated again, newer: https://github.com/Bitmessage/PyBitmessage/pull/1328

**Pull request closed without merging**
