### PR TITLE
Removed 33 E501 line-too-long errors from pycodestyle (3 left).

### PR DESCRIPTION
**Pull request by Jeroenvb3**
Signed-off-by: Jeroen van Bennekum <jeroen_-@live.nl>

## Repository contributions to the PyBitmessage project
Removed some line-too-long errors from the code.

### CODE REVIEW

**Comment by PeterSurda** [comment]
As you can see, it's not easy to fix these code quality issues.

**Comment by Jeroenvb3** [comment]
I can see. I will try to update my code so I don't introduce any new quality errors, and hope that at that point it is a useful addition.

**Comment by PeterSurda** [comment]
This is good work, unfortunately it's difficult to do it in small chunks, so I'll just wait until I get no more complaints from the checks.

**Comment by PeterSurda** [comment]
Due to how the signing works, please rebase to v0.6 instead of merging v0.6. You can also squash your commits, and the commits still aren't signed. You can create a PGP key and upload it to your GitHub profile, and then you can use it for signing.

**Comment by Jeroenvb3** [comment]
I missigned by using the `-s` option instead of `-S`. I hope with my last commit signed it is satisfactory.

I don't understand what you mean by rebasing instead of merging, Github doesn't show me an option to change this, should I make a new PR in order to do this?

In the "Checks" tab of this PR, all checks are passed, is this sufficient? Is it correct to say that these checks are not the same checks as BuildBot reports?

**Comment by PeterSurda** [comment]
> I missigned by using the `-s` option instead of `-S`. I hope with my last commit signed it is satisfactory.

Yes looks ok now.

> I don't understand what you mean by rebasing instead of merging, Github doesn't show me an option to change this, should I make a new PR in order to do this?

I see. I don't know how to do it in the web UI or if it's possible. I do it in the command line. You don't need to make a new PR. If you're having problems with this, let me know and I'll figure something out. But based on previous experience make a copy of your branch in case something goes wrong, so that you don't lose the code :-)

> In the "Checks" tab of this PR, all checks are passed, is this sufficient?

This is a subset of all the tests.

> Is it correct to say that these checks are not the same checks as BuildBot reports?

No, I use two sets of checks, one is from buildbot, and one is a custom check system I wrote, which is can annotate the PR and report in the checks tab.

**Comment by Jeroenvb3** [comment]
Can you show me which commands you use to do it from the command line?

**Comment by Jeroenvb3** [comment]
I rebased, and signed, into a new branch. I made  a new PR for it https://github.com/Bitmessage/PyBitmessage/pull/2057. 
I assume I could have rebased into the current branch but I didn't dare because of the risk to lose all my code :upside_down_face:  .

**Comment by PeterSurda** [comment]
Superseded by #2057

**Pull request closed without merging**
