### PR TITLE
Wrong arguments order in bitmessageqt.MyForm.updateStatusBar()

### PR DESCRIPTION
**Pull request by g1itch**
Hello!

I found that `proofofwork.notifyBuild()` puts arguments into `UISignalQueue` in the wrong order. I added a pseudo test so you can see error message, but to write a proper test I need some special technique, maybe involving `excQueue`.

### CODE REVIEW

**Comment by g1itch** [comment]
Oops, the test shows nothing. Trying to reproduce like here:
https://travis-ci.org/github/g1itch/PyBitmessage/builds/699350113#L994
https://travis-ci.org/github/g1itch/PyBitmessage/builds/708704892#L976

**Comment by g1itch** [comment]
I introduced it in aa333a6

**Comment by g1itch** [comment]
The failure: https://travis-ci.org/github/g1itch/PyBitmessage/builds/735322486

**Review by PeterSurda — APPROVED** [review]
Looks ok.

**Pull request merged**
