### PR TITLE
make interface look more like an e-mail programm, not yet functional

### PR DESCRIPTION
**Pull request by felidosz**
This is not for master-branch, i think i can't request making an branch...

This is a suggestion for making the Interface look more like an e-mail programm.
The your Identities tab contain the folders and you can read your messages on the right. So it looks and works more like Thunderbird. It would be great if you could order your messages with drag and drop ;)
On the send tab you can choose your addresses directly from the left.
The subscribtion messages are separated from the normal messages for understanding the difference of the message types.
On the (new) chanels tab (i used the bitmessage icon temporary) it would be cool if it looks more like a forum, so you could choose a thread (-> subject, with or without 'Re:') on the left and post your comment on the right (Comments separated by '---------' and double posts removed). For now i've just inherited the e-mail and subscribtion behavor.

But i have no more time to bring it to the end. In two month i could do it, but maybe some one other is interested in this interface layout, too ;)

### CODE REVIEW

**Comment by BrokenAltimeter** [comment]
You should include a screenshot to show people what it looks like without them having to clone your branch.

**Comment by felidosz** [comment]
received
send
subscriptions
chanels

**Comment by felidosz** [comment]
received
send
subscriptions
zchanels

**Comment by felidosz** [comment]
The screenshots don't show what works, so here you can see it too ;)

general
 ( ) get message list by folder/type/query

received tab
 (x) new identity button
 ( ) search bar
 ( ) identities context menu
 ( ) list messages by click on folder
 ( ) show message by click on list entry

send tab
 (x) 'send ordinary message' from dropdown
 (x) context menu for addresses
 (x) add contact button
 ( ) search bar
 ( ) add receiver by double clicking on address
 ( ) 'send message to your subscribers' tab from dropdown
 ( ) 'send message to your subscribers' tab send button (choose the right send mode)
 ( ) 'send ordinary message' send button (choose the right send mode)

subscriptions tab
 (x) 'add new subscription' button 
 ( ) search bar
 ( ) show list by clicking on subscription
 ( ) show message by click on list entry

chanels tab
 (x) 'add chanel' button
 ( ) search bar
 ( ) just show chans in chanel list
 ( ) show list by clicking on chan
 ( ) show message by click on list entry

**Pull request closed without merging**
