### PR TITLE
The effects of fc19c54

### PR DESCRIPTION
**Pull request by g1itch**
Hi!

I'm trying to find the possible effects of fc19c54.
I need the buildbot checks with PyQt4 installed to see more, because in my workflow it crashes silently.

### CODE REVIEW

**Comment by PeterSurda** [comment]
The problem appears to be a missing `continue` at `src/class_singleWorker.py` (line 571 in current head).

**Comment by g1itch** [comment]
> The problem appears to be a missing `continue` at `src/class_singleWorker.py` (line 571 in current head).

There are also unneeded nested exception handlers.

**Comment by PeterSurda** [comment]
> There are also unneeded nested exception handlers.

Yes I already gave instructions to reduce these as well.

PS. maybe keep this PR, we do need a test for a broadcast from an address without a key. But you don't have any asserts, maybe there should be an additional status value for such a case that you can check.

**Comment by g1itch** [comment]
This was just a quick hack for an illustration. For the proper test I think a separate test case is needed, outside of the core tests, to not introduce more random failures like in those dontconnect and udp tests.

**Comment by PeterSurda** [comment]
Yea you're right, it's difficult to add tests after weird code has been in production for a long time.

**Pull request closed without merging**
