### PR TITLE
helper_search formating

### PR DESCRIPTION
**Pull request by MahendraNG**
helper_serach formating

### CODE REVIEW

**Comment by MahendraNG** [comment]
Hi g1itch,
In helper_search, there is already search_translate method present and you want me to import from tr import _translate as search_translate.

**Comment by g1itch** [comment]
Exactly, because the function `search_translate` is incomplete duplicate of `tr._translate` and this helper module has nothing to do with Qt.

**Comment by MahendraNG** [comment]
Ok. So shoul I remove the existing function and import this.

**Comment by g1itch** [comment]
Of course, delete the unused code.

**Comment by MahendraNG** [comment]
Sure

**Pull request closed without merging**
