### PR TITLE
Single instance and pop up old instance

### LINKED ISSUE #630: Second bitmessage instance should pop up the window of the first one and quit, and not run in parallel
I launched the second copy of bitmessage from the same user on the same display, and it launched. It showed two windows and two tray icons.

This shouldn't happen. It should locate the first instance, make its window active and quit. Chrome browser, for example, does this.

The second instance also shouldn't be allowed to launch off the same database on another screen, since this doesn't make sense.

It is possible to find the window of the original instance through the window manager.

### PR DESCRIPTION
**Pull request by thelink2012**
Hopefully this fixes #630

### CODE REVIEW

**Comment by thelink2012** [comment]
Works fine on Windows, just tried on Ubuntu and it gives *IOError: [Errno 6] No such device or address: '/home/thelink2012/.config/PyBitmessage/singleton.lock'*, thoughts?

**Comment by PeterSurda** [comment]
Don't use "/", use path.join.

Maybe the error happens because it hasn't created the config directory at that time yet?

**Comment by thelink2012** [comment]
Okay, that seems to be working fine now. I've tested on Windows 8 and Ubuntu 14.04.3 LTS (throught vmware). Please enlight me of any issue.

btw, I'm wasn't entirely sure, but is `myapp.appIndicatorShow()` the correct method to call to bring up the old instance when the new one tries to launch? That seems to work, but still, I have this feeling there should be another method.

**Comment by PeterSurda** [comment]
I'll review it later today.

**Comment by PeterSurda** [comment]
It looks better than the first one, but what about if it is a daemon? It should also not run twice in such a case either.

**Comment by PeterSurda** [comment]
Also, I think `myapp.appIndicatorShow` is the correct method to call.

**Comment by PeterSurda** [comment]
Also, I would kindly ask to PGP-sign your commit, we now have this policy for all commits.

**Comment by thelink2012** [comment]
Oh, didn't notice daemons deleted the singleton that soon. Anyway, fixed.
And PGP signed both commits.

**Comment by PeterSurda** [comment]
Pulled through https://github.com/mailchuck/PyBitmessage/pull/117

I reviewed the code and tested it as far as I could without spending excessive amounts of time. It seems to work. The main windows does not move in front of other windows on Linux or OSX, only on Windows, but that's a separate issue because it misbehaves similarly on other occasions too.

Thanks.

**Pull request closed without merging**
