### PR TITLE
Obsolete helper_generic

### PR DESCRIPTION
**Pull request by g1itch**
Hello.

I moved  `signal_handler()` with it's helper `allThreadTraceback()` into `bitmessagemain` and `powQueueSize()` into `bitmessageqt` because that functions are used only there.

The rest is obsolete.

### CODE REVIEW

**Comment by PeterSurda** [comment]
signal_handler should stay, that is triggered inditectly

**Comment by g1itch** [comment]
> signal_handler should stay, that is triggered inditectly

why it cannot stay in `bitmessagemain` itself?

**Comment by PeterSurda** [comment]
I misread, what you did is probably OK.

**Comment by g1itch** [comment]
In any case `signal.SIGTERM` already [sent](../blob/v0.6/src/tests/test_process.py#L61) in `TestProcessProto.tearDownClass(cls)`. So you can always check if `signal_handler()` was called in Travis CI log:

> 2019-03-06 17:11:24,358 - ERROR - Got signal 15 in MainProcess/MainThread
> 2019-03-06 17:11:24,359 - ERROR - Got signal 15

**Comment by g1itch** [comment]
I'm going to handle `SIGHUP` then.

**Comment by g1itch** [comment]
I can resolve the `unused-argument` pylint warning by changes like
```patch
diff --git a/src/bitmessagemain.py b/src/bitmessagemain.py
index 4a2eff27..76570527 100755
--- a/src/bitmessagemain.py
+++ b/src/bitmessagemain.py
@@ -153,28 +153,37 @@ def _fixSocket():
         socket.IPV6_V6ONLY = 27
 
 
-def allThreadTraceback():
+def allThreadTraceback(thread=None, frame=None):
     # pylint: disable=protected-access
     """Prints traceback from each thread for signal_handler"""
-    id2name = dict([(th.ident, th.name) for th in threading.enumerate()])
-    code = []
-    for threadId, stack in sys._current_frames().items():
-        code.append(
-            '\n# Thread: %s(%d)' % (id2name.get(threadId, ''), threadId))
-        for filename, lineno, name, line in traceback.extract_stack(stack):
-            code.append(
-                'File: "%s", line %d, in %s' % (filename, lineno, name))
+    def traceback_strings(thread, frame):
+        yield '\n# Thread: %s(%d)' % (thread.name, thread.ident)
+        for filename, lineno, name, line in traceback.extract_stack(frame):
+            yield 'File: "%s", line %d, in %s' % (filename, lineno, name)
             if line:
-                code.append('  %s' % (line.strip()))
-    print('\n'.join(code))
+                yield '  %s' % line.strip()
+
+    if not frame:
+        frames = sys._current_frames()
+    if thread:
+        for line in traceback_strings(
+                thread, frame or frames[thread.name]):
+            print(line)
+        return
+
+    threads = {th.ident: th.name for th in threading.enumerate()}
+    for thread_id, frame in frames():
+        for line in traceback_strings(threads[thread_id], frame):
+            print(line)
 
 
 def signal_handler(signum, frame):
     """Single handler for any signal sent to pybitmessage"""
     process = multiprocessing.current_process()
+    thread = threading.current_thread()
     logger.error(
         'Got signal %i in %s/%s',
-        signum, process.name, threading.current_thread().name
+        signum, process.name, thread.name
     )
     if process.name == "RegExParser":
         # on Windows this isn't triggered, but it's fine,
@@ -182,7 +191,7 @@ def signal_handler(signum, frame):
         raise SystemExit
     if "PoolWorker" in process.name:
         raise SystemExit
-    if threading.current_thread().name not in ("PyBitmessage", "MainThread"):
+    if thread.name not in ("PyBitmessage", "MainThread"):
         return
     logger.error("Got signal %i", signum)
     # there are possible non-UI variants to run bitmessage which should shutdown
@@ -190,7 +199,7 @@ def signal_handler(signum, frame):
     if shared.thisapp.daemon or not state.enableGUI:
         shutdown.doCleanShutdown()
     else:
-        allThreadTraceback()
+        allThreadTraceback(thread, frame)
         print('Unfortunately you cannot use Ctrl+C when running the UI'
               ' because the UI captures the signal.')
 
```

**Comment by PeterSurda** [comment]
You can get rid of `allThreadTraceback` entirely. I used it in the past for debugging but I think that there are better tools to do that (pdb, profiling, ...).

**Pull request merged**
