### PR TITLE
german translation and tray icon

### PR DESCRIPTION
**Pull request by felidosz**
german translation and minimize interface on click at tray icon under linux

### CODE REVIEW

**Comment by Atheros1** [comment]
Should this do something on some linux systems? It does nothing on Ubuntu.

**Comment by felidosz** [comment]
Without this change i can't minimize the interface to tray with one click on the tray icon. You have to right click to open the tray menu and then choose show bitmessage.
The "if" enables the minimize-by-one-click-on-the-tray-icon just for windows systems (and disables it for Linux Systems)

Am 22. Februar 2015 03:28:03 MEZ, schrieb Jonathan Warren <notifications@github.com>:

**Comment by Atheros1** [comment]
It doesn't work in Ubuntu for me. I don't think it causes any harm so it should be mergeable but it doesn't work for me. It would be good if someone on OSX could test it.

**Comment by felidosz** [comment]
I have Xubuntu, maybe this is the reason ;)

**Pull request merged**
