### PR TITLE
Reduce windows executable size by excluding unused libs

### PR DESCRIPTION
**Pull request by g1itch**
Hello!

I formatted bitmessagemain.spec and excluded unused libraries. This should slightly reduce the size of windows exe.

### CODE REVIEW

**Review by PeterSurda — APPROVED** [review]
Looks OK, builds succeed. In the future, windows builds will be done automatically for every PR, you can't download the resulting binaries but at least you'll have the build log available.

**Comment by g1itch** [comment]
> Looks OK, builds succeed. In the future, windows builds will be done automatically for every PR, you can't download the resulting binaries but at least you'll have the build log available.

It fails to run on Windows 10. So I don't merge, it needs investigation.

**Comment by PeterSurda** [comment]
64 bit builds for windows 10 aren't working. This is a separate issue and a developer is working on it: #1622

**Comment by g1itch** [comment]
> 64 bit builds for windows 10 aren't working. This is a separate issue and a developer is working on it: #1622

I read it and tested i386 build.

**Comment by g1itch** [comment]
Hmm... Today it runs:
```
2020-10-08 12:29:23,505 - WARNING - Using default logger configuration
2020-10-08 12:29:26,220 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "proofofwork.py", line 306, in init
  File "proofofwork.py", line 117, in _doCPoW
ValueError: Procedure probably called with too many arguments (12 bytes in excess)
2020-10-08 12:29:39,296 - WARNING - C:\Users\D.Bogomolov\AppData\Roaming\namecoin\namecoin.conf unreadable or missing, Namecoin support deactivated
2020-10-08 12:29:39,298 - WARNING - There was a problem testing for a Namecoin daemon. Hiding the Fetch Namecoin ID button
2020-10-08 12:29:39,298 - WARNING - No indicator plugin found
2020-10-08 12:29:39,298 - WARNING - No notification.message plugin found
2020-10-08 12:29:50,905 - WARNING - C:\Users\D.Bogomolov\AppData\Roaming\namecoin\namecoin.conf unreadable or missing, Namecoin support deactivated
2020-10-08 12:29:54,983 - WARNING - There was a problem testing for a Namecoin daemon. Hiding the Fetch Namecoin ID button
2020-10-08 12:40:53,221 - ERROR - UPnP send query failed
Traceback (most recent call last):
  File "upnp.py", line 319, in sendSearchRouter
error: [Errno 10049] 
```

**Comment by g1itch** [comment]
And Bitmessage_x64.exe from https://download2.bitmessage.org/tmp/20200928/ also runs on that machine.

**Comment by PeterSurda** [comment]
The current 64bit binaries don't crash on Windows 10, but they can't send/receive messages because pyelliptic is broken. I still haven't tried running the binaries from this PR.

**Comment by g1itch** [comment]
> The current 64bit binaries don't crash on Windows 10, but they can't send/receive messages because pyelliptic is broken. I still haven't tried running the binaries from this PR.

I see. The date/status of sent message is "Waiting for their encryption key...".

**Comment by PeterSurda** [comment]
> I see. The date/status of sent message is "Waiting for their encryption key...".

Yes, that's how the problem manifests. It can't decode the pubkey object.

**Comment by g1itch** [comment]
> > I see. The date/status of sent message is "Waiting for their encryption key...".
> 
> Yes, that's how the problem manifests. It can't decode the pubkey object.

i386 build behaves in the same way on my machine.

**Comment by PeterSurda** [comment]
> i386 build behaves in the same way on my machine.

It's possible the bug affects other combinations of OS and CPU. However, to get a full test, you have to empty the `inventory` table between trying different versions of the binary / code, or always use an empty config directory. Maybe you haven't done that when switching from 64bit to 32bit binary?

**Comment by g1itch** [comment]
I removed messages.dat and created support request for all three exes: Bitmessage_x64 and _x86 from https://download2.bitmessage.org/tmp/20200928 and my build with this changes. The same result: nothing is sent.

**Comment by PeterSurda** [comment]
ok then, I recommend you can postpone this PR until after pyelliptic is fixed.

**Pull request merged**
