### PR TITLE
uncrumple settings window

### PR DESCRIPTION
**Pull request by dimyme**
full size right away 900 wide now,  with no need to manually enlarge it.

### CODE REVIEW

**Comment by PeterSurda** [comment]
If I understand right, this will prevent it from working correctly on 1024x768. I think that should be the cutoff line.

**Comment by PeterSurda** [comment]
Also squash commits, the commit messages are crap.

**Comment by dimyme** [comment]
what actually is crap is the SPACE py2 grammar sticklers.

**Comment by dimyme** [comment]
> If I understand right, this will prevent it from working correctly on 1024x768. I think that should be the cutoff line.

modded to 900 wide

**Pull request closed without merging**
