### PR TITLE
this way the check will succeed if requirements met

### PR DESCRIPTION
**Pull request by t88yop**
else it will fail with keyError exception, even though everything is satisfied.

### CODE REVIEW

**Comment by PeterSurda** [comment]
Duplicate of #1317

**Comment by PeterSurda** [comment]
I don't think it's PEP8. However, it looks like it does fix the bug.

**Comment by g1itch** [comment]
I think this patch just masks any potential future problems with that evil expression with nested `any([`.

**Comment by PeterSurda** [comment]
@g1itch After reviewing the patch, I agree. This needs to be fixed properly.

**Pull request closed without merging**
