### PR TITLE
Copyright Year

### PR DESCRIPTION
**Pull request by benhc123**
Changed to 2017.

### CODE REVIEW

**Comment by PeterSurda** [comment]
Please review the contribution guidelines: https://bitmessage.org/wiki/Contribute

**Comment by benhc123** [comment]
@PeterSurda I've had a look. As this is just a license date (documentation) update, is it relevant? Thanks.

**Comment by PeterSurda** [comment]
The pull request needs to be against v0.6 branch, and the commits need to be PGP signed.

**Comment by PeterSurda** [comment]
This is now automatic.

**Pull request closed without merging**
