### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by henrikolsson**
Fixes a few typos :)

### CODE REVIEW

**Comment by PeterSurda** [comment]
Thank you,

I am developing on another fork, I'll merge it there and later it will make it into official PyBitmessage.

**Comment by not83** [comment]
Damn you're fast ;)

**Comment by henrikolsson** [comment]
Cool, I saw your reference to https://github.com/mailchuck/PyBitmessage in another pull request. Is that the fork you're talking about? Will it replace this codebase?

**Comment by PeterSurda** [comment]
> Is that the fork you're talking about?
Yes.

> Will it replace this codebase?
Mostly, yes. Almost all commits to that fork will be merged here within the next month or two. With respect to this request, I don't see anything that would be incompatible. If you want, you can make a pull request against that one to speed up the workflow, however I would ask you to PGP sign your commit. Otherwise I have to pull it locally and sign myself.

**Pull request closed without merging**
