### PR TITLE
Appimage build

### PR DESCRIPTION
**Pull request by g1itch**
Hello!

I made a recipe for pkg2appimage and build script for building the AppImage with dependencies inside.

Additional commits are for testing the build and resulting bundle in travis.

### CODE REVIEW

**Comment by g1itch** [comment]
This bundle can run on my Gentoo. Maybe also add python-stem and tor packages?

**Comment by g1itch** [comment]
If I add more dependencies:
```diff
--- a/packages/AppImage/PyBitmessage.yml
+++ b/packages/AppImage/PyBitmessage.yml
@@ -6,10 +6,13 @@ ingredients:
     - deb http://archive.ubuntu.com/ubuntu/ bionic main universe
   packages:
     - python-msgpack
+    - python-qrcode
     - python-setuptools
     - python-sip
     - python-six
+    - python-stem
     - python-qt4
+    - tor
   debs:
     - ../deb_dist/pybitmessage_*_amd64.deb
```
it produces the AppImage of 34.9 MB. The menu_qrcode and proxyconfig_stem are functional.

Unfortunately I cannot fit the [AppImageHub requirements ](https://github.com/AppImage/appimage.github.io#checklist-for-submitting-your-own-appimage), because when I set dist and sources to xenial variant, it produces bundle of about 70 MB, which crashes upon start:
```sh
$ ./PyBitmessage-0.6.3.2.glibc2.15-x86_64.AppImage 
2021-06-05 01:24:34,725 - WARNING - Using default logger configuration
2021-06-05 01:24:34,826 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "/tmp/.mount_PyBitmDasoTi/usr/bin//pybitmessage", line 11, in <module>
    execfile(script_file, new_globals)
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/bitmessagemain.py", line 37, in <module>
    import shutdown
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/shutdown.py", line 11, in <module>
    from network import StoppableThread
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/network/__init__.py", line 4, in <module>
    from addrthread import AddrThread
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/network/addrthread.py", line 9, in <module>
    from network.connectionpool import BMConnectionPool
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/network/connectionpool.py", line 21, in <module>
    from tcp import (
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/network/tcp.py", line 30, in <module>
    from network.tls import TLSDispatcher
  File "/tmp/.mount_PyBitmDasoTi/usr/lib/python2.7/dist-packages/pybitmessage/network/tls.py", line 23, in <module>
    sslProtocolVersion = ssl.PROTOCOL_TLS  # pylint: disable=no-member
AttributeError: 'module' object has no attribute 'PROTOCOL_TLS'
```

It may be related to the deb file, because it's also builds for bionic.

**Comment by g1itch** [comment]
Corresponding checks are: https://git.bitmessage.org/Bitmessage/buildbot-config/pulls/18

**Comment by PeterSurda** [comment]
@g1itch Sorry I edited your comment by mistake and not sure how to revert the edit.

**Comment by g1itch** [comment]
> @g1itch Sorry I edited your comment by mistake and not sure how to revert the edit.

that's OK, in any case there are too few people able to open that link.

**Comment by g1itch** [comment]
> https://buildbot.bitmessage.org/#/builders/14/builds/2874
> 
> ```
> /tmp/.mount_pkg2aphaselr/AppRun: line 424: glib-compile-schemas: command not found
> ```

https://github.com/AppImage/pkg2appimage/blob/master/pkg2appimage#L424 It's strange: as the [manpage](https://manpages.ubuntu.com/manpages/trusty/en/man1/glib-compile-schemas.1.html) says, glib-compile-schemas should be in  libglib2.0-bin, but if I remove it,  `usr/share/glib-2.0/` is got removed as well, so the error shouldn't happen.

**Comment by g1itch** [comment]
Unfortunately I cannot just do `docker run --entrypoint buildscripts/appimage.sh pybm-travis-bionic` because `pkg2appimage` uses fuse, which [cannot run inside a container](https://github.com/AppImage/AppImageKit/issues/405). Seeing how much work is needed to load a maas PXE image into qemu, I'd give up.

**Comment by g1itch** [comment]
Instead I managed to setup github workflow for building appimage, so now you can check the artifact from it's run: https://github.com/g1itch/PyBitmessage/actions/runs/976718400

**Comment by PeterSurda** [comment]
@g1itch The dpkg job runs in a VM, not in a container (as you can see, the worker name contains 'libvirt', whereas the container workers contain 'docker'). In general I want to move workers from VM to a container, but the dpkg job didn't work in docker. I didn't have time to investigate why exactly, rather kept it as a VM. Your PR for updated buildbot config fixes the appimage build and has now been rolled out. Now I just need to make the binaries available.

**Review by PeterSurda — APPROVED** [review]
Works.

**Comment by PeterSurda** [comment]
Binaries are now available at https://appimage.bitmessage.org. The official (master branch of Bitmessage/PyBitmessage) builds are under `releases` and others (e.g. PRs) under `builds`, you can locate yours by the build number.

**Pull request merged**
