### PR TITLE
add pendingDownload and pendingUpload to return of API clientStatus

### PR DESCRIPTION
**Pull request by 813492291816**
adds some information to clientStatus

### CODE REVIEW

**Review by PeterSurda — CHANGES_REQUESTED** [review]
Since `pendingUpload` isn't working correctly now I would remove it from the report. Other than that looks ok.

**Comment by 813492291816** [comment]
Thanks for the feedback. pendingDownload is really what I wanted, but figured I should add pendingUpload as well after seeing network.stats. I've gone ahead and removed pendingUpload.

**Review by PeterSurda — APPROVED** [review]

**Comment by PeterSurda** [comment]
The commits aren't PGP signed. Please sign them and paste your PGP key into your GitHub account's settings.

**Comment by 813492291816** [comment]
Sure. I'm setting it up now and sign my last commit when finished.

**Comment by 813492291816** [comment]
My last commit has been signed and I will sign any future commits.

**Comment by PeterSurda** [comment]
All comments must be signed. Maybe squash, then you can sign easier.

**Comment by 813492291816** [comment]
Thank you for pointing me in the right direction and your patience. I've squashed my two commits into one verified commit.

**Comment by PeterSurda** [comment]
I introduced strict policies about merging for security reasons, so it's more difficult to contribute. However I'd like to update contribution guidelines for a step by step description about how to do that. Most of the checks are already automated so the contributors sees the result directly in the PR, the signatures aren't, but I'll add that too eventually.

**Pull request merged**
