### PR TITLE
QR-code dialog

### PR DESCRIPTION
**Pull request by g1itch**
To open QR-code dialog right click one of you bm-addresses and select "Show QR-code".

### CODE REVIEW

**Comment by PeterSurda** [comment]
Thank you, I like this. Maybe this can be made optional as this requires a new dependency, so that the context menu item would only show up if the qrcode is available?

**Comment by g1itch** [comment]
Yes, I will made changes.

**Comment by PeterSurda** [comment]
If you could also add qrcode as an optional prerequisite to setup.py, that would be great.

**Comment by g1itch** [comment]
With the above changes once `qrcode` installed QR-code menu item will appear. It may sound weird, but I think all optional functionality with additional dependencies may be rewritten as such plugins with extras (opencl support with `pyopencl` and `numpy`, tray menu with `pygobject`, etc).

BTW there is an issue #819

**Comment by PeterSurda** [comment]
Thanks.

**Comment by PeterSurda** [comment]
please rebase, I can't fast-forward merge.

**Comment by PeterSurda** [comment]
Looks ok and I'm happy about the plugin architecture, I wanted to do something like this. But it looks like the plugins have to be installed first (e.g. using setuptools) before it can load them. Can you look at that or should I? Also I'm not sure if it works in frozen mode, have you tried it? I've been having problems with dynamically loading modules in frozen mode (both on Windows and OSX).

**Comment by PeterSurda** [comment]
How about I merge this first and then the other issues are solved separately? If the plugin just doesn't activate in some cases, that's acceptable (as opposed to if it was crashing).

**Pull request merged**
