### PR TITLE
Added: Fabric taskrunner to check python files and report violations

### PR DESCRIPTION
**Pull request by coffeedogs**
A tool to report on code quality, plus some configuration that turns off warnings we don't need to know about right now. This is now ready to merge.

Obsoletes PR#1242, PR#1245 and branches code_quality, code_quality_2.

### CODE REVIEW

**Comment by coffeedogs** [comment]
Not sure why codacy picks up on the redefined __doc__ but pylint doesn't. I am deliberately redefining it for $REASONS. Not sure how to silence it in codacy without trying random lint directives and pushing. Anyone got a good source of docs for where codacy checks for violation exceptions (e.g. setup.cfg, pylintrc, directives in the file, codacy UI)?

**Comment by PeterSurda** [comment]
"We could not find a PyLint configuration file in your project root"

**Comment by coffeedogs** [comment]
Pylint looks at setup.cfg like most other things these days. Is it just a
warning or an error?

**Comment by PeterSurda** [comment]
It's what's preventing me to tell codacy to use a config from the project root instead of the settings that I configure on the codacy website.

**Pull request merged**
